#!/usr/bin/env python
"""Generate project report as .html on Desktop — simple, reliable, browser-friendly."""
import os, sys

DESKTOP = os.path.expanduser("~/Desktop")

CSS = """
body { font-family: 'Microsoft YaHei', Calibri, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #222; line-height: 1.8; }
h1 { font-size: 22pt; text-align: center; margin-bottom: 4pt; color: #1a1a1a; }
.sub { text-align: center; color: #888; font-size: 11pt; margin-bottom: 28pt; }
h2 { font-size: 14pt; color: #1a5276; border-bottom: 2px solid #2980b9; padding-bottom: 4pt; margin-top: 26pt; }
p, li { font-size: 11pt; margin: 5pt 0; }
.find { background: #eaf2f8; border-left: 4px solid #2980b9; padding: 10pt 16pt; margin: 12pt 0; border-radius: 2pt; }
.indent { margin-left: 20pt; }
.good { color: #27ae60; font-weight: bold; }
.warn { color: #e67e22; font-weight: bold; }
.footer { margin-top: 36pt; padding-top: 14pt; border-top: 1px solid #ddd; color: #aaa; font-size: 9pt; text-align: center; }
"""

def build_html(title, subtitle, sections):
    lines = ['<!DOCTYPE html><html><head><meta charset="utf-8">',
             f'<title>{title}</title><style>{CSS}</style></head><body>',
             f'<h1>{title}</h1>',
             f'<p class="sub">{subtitle}</p>']
    in_find = False
    for heading, items in sections:
        lines.append(f'<h2>{heading}</h2>')
        for item in items:
            if item == '':
                continue
            if item.startswith('★'):
                if not in_find:
                    lines.append('<div class="find">')
                    in_find = True
                lines.append(f'<p><b>{item}</b></p>')
            elif item.startswith('[✓]') or item.startswith('[△]') or item.startswith('[✗]'):
                cls = 'good' if '✓' in item else 'warn'
                lines.append(f'<p class="{cls}">{item}</p>')
            elif item.startswith(('  ', '\t', '  •')):
                lines.append(f'<p class="indent">{item.strip()}</p>')
            else:
                if in_find:
                    lines.append('</div>')
                    in_find = False
                lines.append(f'<p>{item}</p>')
        if in_find:
            lines.append('</div>')
            in_find = False
    lines.append('<p class="footer">Generated by Claude Code · HFSS Portfolio Project</p>')
    lines.append('</body></html>')
    return '\n'.join(lines)


if __name__ == '__main__':
    name = sys.argv[1] if len(sys.argv) > 1 else 'PatchAntenna'

    if name == 'PatchAntenna':
        report = {
            'title': '微带贴片天线 @ 2.44GHz — 项目报告',
            'subtitle': '2026-07-09 | v1 (Lp=28.6mm) | FR4 (εr=4.4, h=1.6mm)',
            'file': 'PatchAntenna_v1_Report.html',
            'sections': [
                ('一、设计目标', [
                    '中心频率: 2.44 GHz (WiFi)',
                    'S11 目标: < −10 dB  |  实际: −19.15 dB',
                    '带宽目标: ≥ 80 MHz  |  实际: 50 MHz (2.41–2.46 GHz)',
                    '基板: FR4 (εr=4.4, tanδ=0.02, h=1.6mm, 整体 47×39mm)',
                ]),
                ('二、设计方法', [
                    '1. 初始尺寸 — 传输线模型',
                    '  W = c/(2f₀) × √(2/(εr+1)) = 37.4 mm',
                    '  εeff = 4.08,  ΔL = 0.74 mm',
                    '  L = c/(2f₀√εeff) − 2ΔL = 29.0 mm',
                    '',
                    '2. 内嵌馈电 — 50Ω 阻抗匹配',
                    '  边缘阻抗 ~200Ω → 内嵌深度 y₀: 50 = 200 · cos²(π·y₀/L) → y₀ = 9.3 mm',
                    '  凹槽: 6.1mm宽 × 9.3mm深，馈线宽 3.1mm',
                ]),
                ('三、优化历程', [
                    'v1 | Lp=29.0mm | f₀=2.36 GHz | S11=−6.4 dB — 初始，直接馈电',
                    'v2 | Lp=28.0mm | f₀=2.44 GHz | S11=−6.8 dB — 频率对但未匹配',
                    'v3 | Lp=28.6mm | f₀=2.44 GHz | S11=−19.1 dB — 内嵌馈电 ✅',
                    '',
                    '★ 关键发现: 贴片长度控制谐振频率、内嵌馈电控制阻抗匹配 — 两者独立。',
                ]),
                ('四、最终结果', [
                    '[✓] S11: −19.15 dB (反射 <1.2%)',
                    '[✓] 谐振: 2.44 GHz 精准命中',
                    '[✓] 带宽: 50 MHz (2.41–2.46 GHz), 覆盖 WiFi 2.4G',
                    '[△] 增益: 2 dBi — FR4 材料限制 (tanδ=0.02)',
                ]),
                ('五、面试要点', [
                    '1. 设计了一个 2.44GHz 矩形微带贴片天线：传输线模型计算初始尺寸，内嵌馈电实现 50Ω 匹配。',
                    '2. 最终 S11=−19.15dB，−10dB 带宽 50MHz，尺寸 47×39mm。',
                    '3. 关键理解：贴片长度控制频率、内嵌深度控制匹配；FR4 增益低是材料限制，换 Rogers 可达 5+dBi。',
                ]),
            ],
        }
    elif name == 'Wilkinson':
        report = {
            'title': 'Wilkinson 功分器 @ 2.44GHz — 项目报告',
            'subtitle': '2026-07-13 | v1 | FR4 (εr=4.4, h=1.6mm) | 正交布局',
            'file': 'Wilkinson_v1_Report.html',
            'sections': [
                ('一、设计目标', [
                    '中心频率: 2.44 GHz',
                    'S11 目标: < −10 dB  |  实际: −16.58 dB',
                    'S21/S31 目标: −3 dB ± 1 dB  |  实际: −3.67 dB',
                    '基板: FR4 (εr=4.4, tanδ=0.02, h=1.6mm, 50×60mm)',
                ]),
                ('二、设计方法', [
                    '1. Wilkinson 原理',
                    '  分叉点处两个 50Ω 并联 = 25Ω → 需匹配到 50Ω',
                    '  70.7Ω λ/4 变换器: Zin = Zq²/Zload = 70.7²/50 = 100Ω',
                    '  两个 100Ω 并联 = 50Ω → 输入匹配 ✓',
                    '',
                    '2. 设计参数',
                    '  50Ω 线宽: 3.1 mm | 70.7Ω 线宽: 1.3 mm',
                    '  λ/4 长度: 17 mm (εeff ≈ 3.25)',
                    '  隔离电阻: 100Ω (v2 加入)',
                    '',
                    '3. 全正交布局 (无旋转)',
                    '  输入 50Ω 竖线 → 分叉点 → 两段 70.7Ω 横线 → 输出 50Ω 竖线',
                    '  ★ 关键决策: 取消 45° 旋转，采用全正交布局',
                    '  原因: Lumped Port 要求端口面与走线垂直，旋转导致全反射',
                ]),
                ('三、优化历程', [
                    'v1–v5 | 旋转45° + 各种策略 | S11=−0.27dB | 旋转破坏端口耦合',
                    'v6    | 正交 + Unite       | S11=−16.6dB | ✅ 找到根因',
                    '',
                    '★ 核心教训: 端口面必须垂直于走线方向 — 这是 HFSS Lumped Port 的关键约束。',
                    '  旋转看似优美，但端口积分线无法跟随旋转，导致信号全反射。',
                    '  通过 5 轮诊断性测试 (thru→3port→diag→tee→正交) 最终定位。',
                ]),
                ('四、最终结果', [
                    '[✓] S11: −16.58 dB — 匹配优秀',
                    '[✓] S21: −3.67 dB — 等分',
                    '[✓] S31: −3.67 dB — 与 S21 完全一致',
                    '[△] S23: −7.59 dB — 无隔离电阻 (v2 优化)',
                    '',
                    '额外 0.67 dB 损耗: FR4 介质损耗 + 铜损耗 + 结不连续性',
                    '与贴片天线同频段 (2.44GHz)、同基板 (FR4)，形成作品集系列',
                ]),
                ('五、面试要点', [
                    '1. 设计了一个 2.44GHz Wilkinson 功分器：λ/4 70.7Ω 阻抗变换，全正交布局。',
                    '2. S11=−16.6dB，功率等分 −3.67dB/每路，与贴片天线同频同基板形成系列。',
                    '3. 关键理解: λ/4 变换 + 隔离电阻 = Wilkinson 核心；',
                    '   工程上，Lumped Port 与走线的垂直关系是仿真成败的关键约束。',
                ]),
            ],
        }
    else:
        print(f'Unknown: {name}')
        sys.exit(1)

    html = build_html(**{k: v for k, v in report.items() if k != 'file'})
    path = os.path.join(DESKTOP, report['file'])
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f'OK: {path}')
